### ISSUE TITLE
Use this plugin with Twilio

### ISSUE THREAD

**Issue by bijalmenon** [CoSMoSoftware/CSM-IE-WebRTC-plugin-shim#1]
Hi,

I am using Twilio javascript SDK for web rtc and was trying to use this plug-in for IE. I have used registered the plug-in as mentioned. However, still not able to access the camera and microphone. Could you please guide.

**Comment by agouaillard-cosmo** [comment]
We are in the process of upgrading this code. Please reevaluate after the next release, and open a new bug if still needed.
