### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Igor-Techsee** [CoSMoSoftware/CSM-IE-WebRTC-plugin-shim#3]
Is this still maintained? Is this plugin will work on all windows with ie11 or only on specific versions? Any information you can provide me would be greatly appreciated.

**Comment by agouaillard-cosmo** [comment]
It is still maintained.
It has been developed specifically for IE 11 on win 7.

**Comment by Igor-Techsee** [comment]
Thanks! Is there any chance that this plugin will work on windows 8 and later Windows versions?

**Comment by agouaillard-cosmo** [comment]
It should work on windows 8.
It might work on win10.
