### ISSUE TITLE
Dynamically created video elements

### ISSUE THREAD

**Issue by alexdn-techsee** [CoSMoSoftware/CSM-IE-WebRTC-plugin-shim#4]
Hey, I succeed to use this shim with plugin to see the video in IE11 browser, but it only worked with video elements that were on html during load. When adding stream to video element created in runtime, video is not shown. I noticed there no "object" tag added to runtime video element.

Does it known issue or I'am missing something and my use case should work also?

Thanks!

**Comment by agouaillard-cosmo** [comment]
We re in the process of upgrading the plugin code. I;m closing this bug for now; please re-evaluate after the next release.
